### ISSUE TITLE
st_connect use improper for unprojected objects

### ISSUE THREAD

**Issue by rsbivand** [michaeldorman/nngeo#12]
The warnings on CRAN are coming from sp (or sf if st_connect uses st_sample) about *sample being used on unprojected data:

The warnings seem to appear in nngeo::st_connect() in the lapply() local  function starting at line 97 in nngeo/R/st_connect.R, and come from sp:::sample.SpatialLines, sp/R/spsample.R line 177:
```
        if (isTRUE(!is.projected(x)))
                warning("working under the assumption of projected data!")
```
In fact the warning should be issued in all cases as far as I can see, nngeo is sampling from a line on the ellipsoid but assuming planar geometry. They might also switch from sp to sf for the spatial sampling:
```
#      x_sp = as(x[i], "Spatial")
#      start_pool = sp::spsample(x_sp, type = "regular", n = n_x[i])
#      start_pool = st_as_sfc(start_pool)
       start_pool = st_sample(x[i], type = "regular", size = n_x[i])
```
and
```
#        y_sp = as(y[j], "Spatial")  
#        end_pool = sp::spsample(y_sp, type = "regular", n = n_y[j])
#        end_pool = st_as_sfc(end_pool)
        end_pool = st_sample(y[i], type = "regular", size = n_y[i])
```
in nngeo/R/st_connect.R: with sf 0.8-1, the vignette gets three:

`#> although coordinates are longitude/latitude, st_sample assumes that they are planar`

messages.

So the underlying problem is the misuse of sp::spsample or sf::st_sample on unprojected data.

**Comment by michaeldorman** [comment]
Thank you very much for looking into this and for the helpful comments!

The modified `st_connect` function:
1. uses `sf::st_nearest_points` to find the nearest points, so that sampling with `sp::spsample` is no longer required; and
2. sets CRS to `NA` before passing the geometries to `sf::st_nearest_points` in order to avoid the warning `although coordinates are longitude/latitude, st_nearest_points assumes that they are planar`

That way the nearest points calculation is "forced" to be planar.

Accordingly, I added a note to emphasize that the calculation is aimed at graphical display of matching features, therefore the calculated line segments are intentionally planar regardless of the CRS:

```
The segments are straight lines, i.e., they correspond to shortest path assuming 
planar geometry regardless of CRS. Therefore, the lines should serve as a 
graphical indication of features that are nearest to each other; the exact shortest 
path between features should be calculated by other means, such as 
`geosphere::greatCircle`.
```

I hope that this solves the issue.

**Comment by rsbivand** [comment]
A remark - if the segment crosses the antimeridian, the assumption of planarity will lead to odd outcomes (I haven't checked that operating on the sphere actually works, see: https://github.com/r-spatial/global). And congratulations on your book!

I can't tell whether the revisions will be enough, but if the vignette re-builds when R packages are using GDAL3 and PROJ3 without issues, then probably OK (PROJ and GDAL are very fast-moving now, so the versions I use, Edzer uses, and CRAN gets (for Debian) are not necessarily the same).

**Comment by michaeldorman** [comment]
Thank you very much!

This is a good point that I haven't considered. I understand that crossing the antimeridian would lead to odd lines, representing a much longer path than the true shortest one. However, the result is still correct in terms of the `st_connect` function purpose: the lines reflect the agreement between geometries which are indeed nearest. 

An alternative is to draw a line that "goes out" of the plot extent and resumes on the other side. I'm not sure that it would be better, because then it may be difficult to follow where each line goes if there are many such lines in the same plot. In any case, I'm looking forward to developments with the `global` package to try this out.

Here is a reproducible example of what happens when matching geometries are near the antimeridian on opposite sides:

``` r
library(nngeo)

# Read data
url = "https://gist.githubusercontent.com/michaeldorman/7c0cf61f92449c2e0f7323626bf1a131/raw/f651534d25d498a65697062b27de316f5b8b2531/map.geojson"
dat = st_read(url)
```

    ## Reading layer `map' from data source `https://gist.githubusercontent.com/michaeldorman/7c0cf61f92449c2e0f7323626bf1a131/raw/f651534d25d498a65697062b27de316f5b8b2531/map.geojson' using driver `GeoJSON'
    ## Simple feature collection with 6 features and 0 fields
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: -162.4219 ymin: -33.72434 xmax: 138.5156 ymax: 74.21198
    ## epsg (SRID):    4326
    ## proj4string:    +proj=longlat +datum=WGS84 +no_defs

``` r
dat1 = dat[1:2, ]
dat2 = dat[3:6, ]

# Calculate lines to nearest
lines = st_connect(dat1, dat2)

# Plot
library("rnaturalearth")
world = ne_countries(scale = "small", returnclass = "sf")
world = st_geometry(world)
plot(world, border = "grey")
plot(st_geometry(dat1), col = "red", add = TRUE)
plot(st_geometry(dat2), col = "blue", add = TRUE)
plot(lines, add = TRUE)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/73640592-3441c700-4677-11ea-8e63-323e86b2afd0.png)

**Comment by rsbivand** [comment]
I think that `global` will provide better options, for now neither is visually attractive, unless maybe shifting to a "Pacific" view?

**Comment by michaeldorman** [comment]
Shifting the perspective is an interesting idea, thanks. I'll think about it.

**Comment by rsbivand** [comment]
Maybe https://github.com/r-spatial/sf/pull/1218 `st_shift_longitude()` in today's release of **sf**? https://twitter.com/edzerpebesma/status/1224273882045145088

**Comment by michaeldorman** [comment]
Good to know!

This works fine for the points and lines, will try to figure out how to work with polygonal data to plot them correctly:

``` r
library(nngeo)

# Read data
url = "https://gist.githubusercontent.com/michaeldorman/7c0cf61f92449c2e0f7323626bf1a131/raw/f651534d25d498a65697062b27de316f5b8b2531/map.geojson"
dat = st_read(url)
```

    ## Reading layer `map' from data source `https://gist.githubusercontent.com/michaeldorman/7c0cf61f92449c2e0f7323626bf1a131/raw/f651534d25d498a65697062b27de316f5b8b2531/map.geojson' using driver `GeoJSON'
    ## Simple feature collection with 6 features and 0 fields
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: -162.4219 ymin: -33.72434 xmax: 138.5156 ymax: 74.21198
    ## epsg (SRID):    4326
    ## proj4string:    +proj=longlat +datum=WGS84 +no_defs

``` r
dat1 = dat[1:2, ]
dat2 = dat[3:6, ]

# Calculate lines to nearest
lines = st_connect(dat1, dat2)

# World data
library("rnaturalearth")
world = ne_countries(scale = "small", returnclass = "sf")
world = st_geometry(world)
world = st_cast(world, "MULTILINESTRING")
world = st_wrap_dateline(world)

# Shift to "Pacific" view
dat = st_shift_longitude(dat)
dat1 = st_shift_longitude(dat1)
dat2 = st_shift_longitude(dat2)
lines = st_shift_longitude(lines)
world = st_shift_longitude(world)

# Plot
plot(st_geometry(dat), col = NA)
plot(world, col = "grey", add = TRUE)
plot(st_geometry(dat1), col = "red", add = TRUE)
plot(st_geometry(dat2), col = "blue", add = TRUE)
plot(lines, add = TRUE)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/73657988-19357e00-469c-11ea-98fe-3c27edf2f43d.png)
