### ISSUE TITLE
Finding no of neighbours within a certain distance

### ISSUE THREAD

**Issue by richardohrvall** [michaeldorman/nngeo#19]
Thank you once again for a great package!

This might be beyond the scope of the package and not of interest to you, but I thought I should mention it anyway. I think it would be valuable to have the possibility to find how many neighbours there are within a certain, specified distance. I assume this could be achieved by setting a very high k, and then adding up the number of neighbours within each observation. And there are of course other ways to calculate this. But it would be very convenient with an additional function in nngeo that adds the number of neighbours within distance d, as a new variable to the data frame.  It might be just my field, but there this type of calculation is very common. 

But there might be problems with this idea that I don't grasp.

All the best, Richard

**Comment by michaeldorman** [comment]
Hi Richard,

The number of neighbors within distance `d` can be extracted from the object containing neighbor indices returned by `st_nn`, using base function `lengths`, since the number of indices is in fact the number of neighbors. Like you said, this requires setting a large `k`, equal to the maximal number of neighbors possible which is `nrow(y)`.

Please see below small reproducible example:

```r
library(nngeo)
ids = st_nn(cities, towns, k = nrow(towns), maxdist = 12000)
cities$n = lengths(ids)
```

Now, layer `cities` has an additional column named `n` with the number of `towns` features up to distance 12,000 m:

```r
cities
## Simple feature collection with 3 features and 2 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 34.78177 ymin: 31.76832 xmax: 35.21371 ymax: 32.79405
## Geodetic CRS:  WGS 84
##        name                  geometry  n
## 1 Jerusalem POINT (35.21371 31.76832)  5
## 2  Tel-Aviv  POINT (34.78177 32.0853) 18
## 3     Haifa POINT (34.98957 32.79405)  9
```

Best regards,

Michael

**Comment by richardohrvall** [comment]
Thank you for the very prompt and informative reply!

It was a very elegant solution. I have to check if it is more efficient than my previous approach with st_buffer and then checking for overlaps.

All the best, Richard
