### ISSUE TITLE
Distance polygon to point: rule for ordering within polygon, and speed?

### ISSUE THREAD

**Issue by MatthieuStigler** [michaeldorman/nngeo#7]
Hi

Very nice package, thanks! I was using distance from point to polygons, and have a few questions:

1. I see that points within polygon have distance of 0. Does this mean ordering for those is arbitrary?
2. Speed: doing point to polygon is much slower than point to centroid. Is this because the `st_dist()` is used on the full dataset? Interestingly, `st_contains()` seems much faste. Could that be used to restrict the dimensionality of the search (st_contain to get inner point, if n_inner<k, get distance on outer ones?)

Thanks!

**Comment by michaeldorman** [comment]
Hi Matthieu, 

Thanks for your interest and useful suggestions!

1. When there are ties in terms of distances, the ordering should be according to the order of the original features. For example, if there are three points inside a polygon, and we search for the nearest two, these are going to be the top two in the points geometry column:

``` r
library(nngeo)

# Create polygon
p1 = st_point(c(0,0))
p2 = st_point(c(0,1))
p3 = st_point(c(1,1))
p4 = st_point(c(1,0))
pol = c(p1, p2, p3, p4)
pol = st_cast(pol, "POLYGON")
pol = st_sfc(pol)
pol
```

    ## Geometry set for 1 feature 
    ## geometry type:  POLYGON
    ## dimension:      XY
    ## bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
    ## epsg (SRID):    NA
    ## proj4string:    NA

    ## POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))

``` r
# Create points
p1 = st_point(c(0.1,0.7))
p2 = st_point(c(0.5,0.8))
p3 = st_point(c(0.9,0.6))
pnt = c(p1, p3, p2)
pnt = st_sfc(pnt)
pnt = st_cast(pnt, "POINT")
pnt
```

    ## Geometry set for 3 features 
    ## geometry type:  POINT
    ## dimension:      XY
    ## bbox:           xmin: 0.1 ymin: 0.6 xmax: 0.9 ymax: 0.8
    ## epsg (SRID):    NA
    ## proj4string:    NA

    ## POINT (0.1 0.7)

    ## POINT (0.9 0.6)

    ## POINT (0.5 0.8)

``` r
# Find nearest
n = st_nn(pol, pnt, k = 2, progress = FALSE)

# Plot
plot(pol, xlim = c(0, 1), ylim = c(0, 1.3))
plot(pnt, add = TRUE)
text(st_coordinates(pnt), as.character(1:3), pos = 1)
text(st_coordinates(pnt[n[[1]]]), as.character(n[[1]]), col = "red", pos = 3)
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/67157125-7812f980-f330-11e9-9d0a-470b161a8205.png)

2. I see your point that in particular scenarios, where many of the points are within polygons, this can make the calculation faster. However this seems to me a rare case: usually one wants to either find the points inside polygons (which can simply be done with `st_contains`), or the nearest points outside of the polygons (in which case the internal points can be first eliminated with `!st_contains` and then the nearest external points can be detected with `st_nn`. 

Anyway, I modified the `st_nn_poly` code as follows to try out your suggestion:

```r
# Distances for feature 'i'
dists = rep(NA, y_features)

# If intersects, dist=0
intersects = sf::st_intersects(x[i], y, sparse = FALSE)[1, ]
dists[intersects] = 0

# Otherwise, calculate dist
dists[!intersects] = sf::st_distance(x[i], y[!intersects])[1, ]
```

And tested on a small reproducible example as follows:

```r
library(nngeo)

# Polygon
pol = st_read(system.file("shape/nc.shp", package="sf"))
pol = st_geometry(pol)

# Create points
set.seed(1)
pnt = st_sample(st_as_sfc(st_bbox(pol)), 10000)

# Find nearest
start = Sys.time()
n = st_nn(pol, pnt, k = 10, progress = FALSE)
end = Sys.time()
end - start
```

Timing comes out almost identical, because the proportion of points within any particular polygon is rather small, so most distances still need to be calculated. 

If you have an example where you think the gain will be substantial I will be happy to try.

**Comment by MatthieuStigler** [comment]
HI Michael

Thanks for your response, much appreciated! The use case for me was to run a locally-weighted regression: I basically discretize my space with a grid, then within each grid compute my regression of interest. As some cells are very sparse, I need to take points from neighboring cells (i.e. outside polygons). 

Here would be a similar code to run it:

> 
> library(nngeo)
> library(sf)
> 
> ##
> nc = st_read(system.file("shape/nc.shp", package="sf"))
> nc1 <- nc[2,]
> 
> set.seed(123)
> p1 = st_sample(nc[1:3, ], 5000)
> 
> ## distances
> k_10 <- st_nn(st_geometry(nc), p1, k=500)

**Comment by michaeldorman** [comment]
Thanks!

I checked, and this particular example is actually faster with the existing code:

```r
dists = sf::st_distance(x[i], y)[1, ]
```

(16 seconds)

than with the alternative version which first finds zero distances:

```r
# Distances for feature 'i'
dists = rep(NA, y_features)
# If intersects, dist=0
intersects = sf::st_intersects(x[i], y, sparse = FALSE)[1, ]
dists[intersects] = 0
# Otherwise, calculate dist
dists[!intersects] = sf::st_distance(x[i], y[!intersects])[1, ]
```

(26 seconds)

**Comment by MatthieuStigler** [comment]
I forgot to answer on that, but indeed after trying multiple scenarios, it seems the direct approach is still faster. 

Thanks for having a look at that!
